# Site settings
title: =.=
description: mm 
cover: assets/images/radhakrishna.jpg
logo: assets/images/tree.png
favicon: assets/images/tree.png
baseurl: "/eehh/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://wangziweiwangziwei.github.io" # the base hostname & protocol for your site
paginate:	50 # The number of posts to show per page on your homepage

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: wangziweiwangziwei #github username
repo: eehh  #github repository
branch: master #branch
relative_source: ../eehh/ #source directory
destination: ../eehh/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://github.com/wangziweiwangziwei/eehh  #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
